
import type { Metadata } from "next";
import { AntdRegistry } from '@ant-design/nextjs-registry';

import { Inter } from "next/font/google";
import "./globals.css";
import { Content } from "antd/es/layout/layout";
import { ConfigProvider, Layout } from "antd";


import MainSider from "./MainSider/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



const colorPrimary = "#ac46ff";
const colorInfo = "#ac46ff";



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AntdRegistry>
          <ConfigProvider

            theme={{
              "token": {
                colorPrimary,
                colorInfo,
              }
            }}>

            <Layout hasSider>
              <MainSider />
              <Layout>

                <Content style={{ overflow: 'hidden', overflowY: "auto", height: "calc(100dvh)" }}>
                  <div
                    style={{

                      padding: 24,
                      borderRadius: "20px",
                    }}
                  >

                    {children}
                  </div>
                </Content>

              </Layout>
            </Layout>
          </ConfigProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
